name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          for d in python; do
            echo Zipping $d
            (cd $d && zip -r ../$d.zip .)
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
